### ISSUE TITLE
Wrong url install php

### ISSUE THREAD

**Issue by jhamilius** [yclas/docker#6]
https://raw.githubusercontent.com/open-classifieds/openclassifieds2/master/install-openclassifieds.php is not available anymore.
https://raw.githubusercontent.com/yclas/yclas/master/install-yclas.php is the new one

**Comment by neo22s** [comment]
@jhamilius thanks!!! @kotsios5 will fix it now ;)

**Comment by neo22s** [comment]
https://raw.githubusercontent.com/yclas/yclas/master/install-yclas.php

**Comment by neo22s** [comment]
fixed ;)

**Comment by jhamilius** [comment]
Thanks :) @neo22s
